name: Execute example notebook
on:
  workflow_dispatch:
  pull_request:
    branches:
    - "main"
  push:
    branches:
    - "dev"
jobs:
  nbconvert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - name: Install poetry
      run: |
        curl -sSL https://install.python-poetry.org | python -
        poetry --version
    - name: Install dependencies with poetry
      run: |
        poetry install
    - name: Execute crspectra.ipynb with nbconvert
      run: |
        poetry run jupyter nbconvert \
          --to notebook \
          --inplace \
          --execute example/crspectra.ipynb
    - uses: actions/upload-artifact@v3
      with:
        path: example/crspectra.png
